<!-- Highlighted Topic Heading -->
<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0; font-weight:bold;">
1. Matrix and Vector Operations
</div>

<!-- Task Description -->
<div style="background-color:#f0f0f0; color:black; padding:10px 10px 10px 20px; margin:10px 0;">

<ol style="margin:0; padding-left:20px;">
  <li>
    Create a 3 × 3 matrix A and a 3 × 1 vector B:<br><br>
    A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]<br>
    B = [1, 2, 3]<br><br>
    Tasks:<br>
    <ul>
      <li>Perform matrix-vector multiplication A × B.</li>
      <li>Calculate the trace of matrix A (sum of diagonal elements).</li>
      <li>Find the eigenvalues and eigenvectors of A.</li>
    </ul>
  </li>
  <li>
    Replace the last row of matrix A with [10, 11, 12] and:<br>
    <ul>
      <li>Compute the determinant of the updated matrix A.</li>
      <li>Identify if the updated matrix is singular or non-singular.</li>
    </ul>
  </li>
</ol>

</div>


In [3]:
import numpy as np

# Defining matrix A and vector B
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([1, 2, 3])

#  Matrix-vector multiplication
result = np.dot(A, B)

# Calculation of the trace of matrix A
trace_A = np.trace(A)

# eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print 
print("Matrix-Vector Multiplication (A x B):\n", result)

print("Trace of Matrix A:", trace_A)

print("Eigenvalues of A:\n", eigenvalues)

print("Eigenvectors of A:\n", eigenvectors)


Matrix-Vector Multiplication (A x B):
 [14 32 50]
Trace of Matrix A: 15
Eigenvalues of A:
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvectors of A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


# ---------------------------------------------------------------------------------------------------------

In [4]:
import numpy as np

# Defining matrix A and vector B
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Replacing the last row of matrix A
A[2] = [10, 11, 12]

# Computing the determinant of updated A
det_A = np.linalg.det(A)

# Checking if the matrix is singular 
if np.isclose(det_A, 0):
    status = "Singular (Non-Invertible)"        
else:
    status = "Non-Singular (Invertible)"

# Print 
print("Updated Matrix A:\n", A)

print("Determinant of Updated Matrix A:", det_A)

print("Matrix Status:", status)


Updated Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
Determinant of Updated Matrix A: 2.86437540353291e-15
Matrix Status: Singular (Non-Invertible)


# =============================================================

<!-- Highlighted Topic Heading -->
<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0; font-weight:bold;">
2. Invertibility of Matrices
</div>

<!-- Task Description -->
<div style="background-color:#f0f0f0; color:black; padding:10px 10px 10px 20px; margin:10px 0;">

<ol style="margin:0; padding-left:20px;">
  <li>
    Verify the invertibility of the updated matrix A:<br>
    <ul>
      <li>Check if the determinant is non-zero.</li>
      <li>If invertible, calculate the inverse of A.</li>
    </ul>
  </li>
  <li>
    Solve a system of linear equations \( A \times X = B \), where:<br>
    <ul>
      <li>\( A \) is the updated matrix.</li>
      <li>\( B \) is a \( 3 \times 1 \) matrix:
        <br>
        <div style="text-align:center; margin-top:5px;">
        $$ B = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} $$
        </div>
      </li>
    </ul>
  </li>
</ol>

</div>



In [11]:
import numpy as np

# Updated matrix A
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [10, 11, 12]])  

# Computing the determinant of A
det_A = np.linalg.det(A)

# Checking if the matrix is invertible
if np.isclose(det_A, 0):  
    status = "Singular (Non-Invertible)"
    inverse_A = "Not possible (Matrix is singular)"
else:
    status = "Non-Singular (Invertible)"
    inverse_A = np.linalg.inv(A)  

# Print 
print("Updated Matrix A:\n", A)
print(50*"=")
print("Determinant of Updated Matrix A:", det_A)
print(50*"=")
print("Matrix Status:", status)
print(50*"=")
print("Inverse of Matrix A:\n", inverse_A)


Updated Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
Determinant of Updated Matrix A: 2.86437540353291e-15
Matrix Status: Singular (Non-Invertible)
Inverse of Matrix A:
 Not possible (Matrix is singular)


# ---------------------------------------------------------------------------------------------------------

In [12]:
import numpy as np

# Defining the updated matrix A
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [10, 11, 12]])  

# Defining the vector B (3×1)
B = np.array([[1], 
              [2], 
              [3]])

# Computing determinant of A
det_A = np.linalg.det(A)

# Proceeding with solving for X only if A is invertible
if np.isclose(det_A, 0):
    solution = "No unique solution (Matrix is singular)"
else:
    solution = np.linalg.solve(A, B)  

# Print 
print("Updated Matrix A:\n", A)
print("="*50 )  

print("Vector B:\n", B)
print("="*50 )  

print("Determinant of Updated Matrix A:", det_A)
print("="*50 )  

print("Solution X:\n", solution)


Updated Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
Vector B:
 [[1]
 [2]
 [3]]
Determinant of Updated Matrix A: 2.86437540353291e-15
Solution X:
 No unique solution (Matrix is singular)


# ==========================================================

<!-- Highlighted Topic Heading -->
<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0; font-weight:bold;">
3. Practical Matrix Operations
</div>

<!-- Task Description -->
<div style="background-color:#f0f0f0; color:black; padding:10px 10px 10px 20px; margin:10px 0;">

<ol style="margin:0; padding-left:20px;">
  <li>
    Create a 4 × 4 matrix C with random integers between 1 and 20:<br><br>
    <code>C = np.random.randint(1, 21, size=(4, 4))</code><br><br>
    Tasks:<br>
    <ul>
      <li>Compute the rank of C.</li>
      <li>Extract the submatrix consisting of the first 2 rows and last 2 columns of C.</li>
      <li>Calculate the Frobenius norm of C.</li>
    </ul>
  </li>
  <li>
    Perform matrix multiplication between A (updated to 3 × 3) and C (trimmed to 3 × 3):<br>
    <ul>
      <li>Check if the multiplication is valid.</li>
      <li>If not, reshape C to make it compatible with A.</li>
    </ul>
  </li>
</ol>

</div>


In [13]:
import numpy as np

# Creating a 4 × 4 matrix C with random integers from 1 to 20
C = np.random.randint(1, 21, size=(4, 4))

# Computing the rank of C
rank_C = np.linalg.matrix_rank(C)

# Extracting the submatrix (first 2 rows, last 2 columns)
submatrix = C[:2, -2:]  

# Computing the Frobenius norm of C
frobenius_norm = np.linalg.norm(C, 'fro')

# Print 
print("Matrix C:\n", C)
print(  "="*40 ) 

print("Rank of Matrix C:", rank_C)
print(  "="*40 ) 

print("Extracted Submatrix (First 2 rows, Last 2 columns):\n", submatrix)
print(  "="*40 ) 

print("Frobenius Norm of Matrix C:", frobenius_norm)


Matrix C:
 [[17  8  6  4]
 [ 6  2 15 20]
 [15 18  8  1]
 [ 9  3 19 10]]
Rank of Matrix C: 4
Extracted Submatrix (First 2 rows, Last 2 columns):
 [[ 6  4]
 [15 20]]
Frobenius Norm of Matrix C: 47.275786614291256


# ---------------------------------------------------------------------------------------------------------

In [14]:
import numpy as np

#  3 × 3 matrix A
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [10, 11, 12]])  

# Generating a 4 × 4 matrix C
C = np.random.randint(1, 21, size=(4, 4))

print("Original Matrix C (4 × 4):\n", C)
print(  "="*40 ) 

# Trimmed C to 3 × 3 
C_trimmed = C[:3, :3]

print("Trimmed Matrix C (3 × 3):\n", C_trimmed)
print(  "="*40 )  

# Performing matrix multiplication A × C_trimmed
result = np.dot(A, C_trimmed)  

print("Matrix Multiplication Result (A × C_trimmed):\n", result)


Original Matrix C (4 × 4):
 [[17  3 19 13]
 [18 18 15  1]
 [12  3  6 15]
 [ 7  9  7 10]]
Trimmed Matrix C (3 × 3):
 [[17  3 19]
 [18 18 15]
 [12  3  6]]
Matrix Multiplication Result (A × C_trimmed):
 [[ 89  48  67]
 [230 120 187]
 [512 264 427]]


# ============================================================

<!-- Highlighted Topic Heading -->
<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0; font-weight:bold;">
4. Data Science Context
</div>

<!-- Task Description -->
<div style="background-color:#f0f0f0; color:black; padding:10px; margin:10px 0;">
1. Create a dataset as a 5 × 5 matrix D, where each column represents a feature, and each row represents a data point:<br><br>

D = np.array([[3, 5, 7, 9, 11],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2, 4, 6, 8, 10],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1, 3, 5, 7, 9],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[4, 6, 8, 10, 12],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[5, 7, 9, 11, 13]])<br><br>

Tasks:<br>
- Standardize D column-wise (mean = 0, variance = 1).<br>
- Compute the covariance matrix of D.<br>
- Perform Principal Component Analysis (PCA):<br>
&nbsp;&nbsp;&nbsp;&nbsp;- Find the eigenvalues and eigenvectors of the covariance matrix.<br>
&nbsp;&nbsp;&nbsp;&nbsp;- Reduce D to 2 principal components.
</div>


In [15]:
import numpy as np

# Creating the dataset D 
D = np.array([[3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10],
              [1, 3, 5, 7, 9],
              [4, 6, 8, 10, 12],
              [5, 7, 9, 11, 13]])

print("Original Dataset D (5 × 5):\n", D)
print( "="*50 )

# Standardizing D (column-wise: mean = 0, variance = 1)
D_mean = np.mean(D, axis=0)                                                            # Mean of each column
D_std = np.std(D, axis=0, ddof=1)                                                      # Standard deviation of each column

D_standardized = (D - D_mean) / D_std  

print("Standardized D (Mean = 0, Variance = 1):\n", D_standardized)
print( "="*50 )

# Computing the covariance matrix of D_standardized
cov_matrix = np.cov(D_standardized, rowvar=False)  

print("Covariance Matrix of D:\n", cov_matrix)
print( "="*50 )

# Performing PCA 
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)
print( "="*50 )

#  Reducing D to 2 Principal Components
# Sorting eigenvalues and eigenvectors in descending order

sorted_indices = np.argsort(eigenvalues)[::-1]  
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# Selecting the top 2 eigenvectors 
top_2_eigenvectors = eigenvectors[:, :2]

# Projecting D onto the top 2 principal components
D_pca = D_standardized @ top_2_eigenvectors

print("Dataset D reduced to 2 Principal Components:\n", D_pca)


Original Dataset D (5 × 5):
 [[ 3  5  7  9 11]
 [ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [ 4  6  8 10 12]
 [ 5  7  9 11 13]]
Standardized D (Mean = 0, Variance = 1):
 [[ 0.          0.          0.          0.          0.        ]
 [-0.63245553 -0.63245553 -0.63245553 -0.63245553 -0.63245553]
 [-1.26491106 -1.26491106 -1.26491106 -1.26491106 -1.26491106]
 [ 0.63245553  0.63245553  0.63245553  0.63245553  0.63245553]
 [ 1.26491106  1.26491106  1.26491106  1.26491106  1.26491106]]
Covariance Matrix of D:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Eigenvalues:
 [ 5.00000000e+00  1.14734539e-16  9.86076132e-32  0.00000000e+00
 -4.86380468e-64]

Eigenvectors:
 [[-4.47213595e-01 -4.43967828e-01 -2.61651409e-16 -5.94126114e-33
   4.28171276e-17]
 [-4.47213595e-01 -6.40813725e-01 -8.66025404e-01  1.15464331e-16
  -2.15306790e-01]
 [-4.47213595e-01  3.61593851e-01  2.88675135e-01 -9.91950729e-17
  -7.19091634e-01]
 [-4.47213595e-01  3.61593851e-01  2.8