<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0;">
1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:<br>
&nbsp; a. Calculate the sum, mean, median, and standard deviation of the elements in the array.<br>
&nbsp; b. Find the indices of elements greater than 10 in the array.
</div>


In [1]:
import numpy as np

# Creating a 1D NumPy array with integers from 1 to 20
arr = np.arange(1, 21)

# a. Calculating sum, mean, median, and standard deviation

arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_median = np.median(arr)
arr_std = np.std(arr)

print(f"Sum: {arr_sum}")
print(f"Mean: {arr_mean}")
print(f"Median: {arr_median}")
print(f"Standard Deviation: {arr_std}")

print("===================================================================")

# b. Finding indices of elements greater than 10

indices_greater_than_10 = np.where(arr > 10)[0]

print(f"Indices of elements greater than 10: {indices_greater_than_10}")


Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements greater than 10: [10 11 12 13 14 15 16 17 18 19]


<div style="background-color:#00008B; color:white; padding:10px; margin:10px 0;"> This code creates a NumPy array with numbers from 1 to 20. Then, it calculates some important values: the sum, mean (average), median (middle value), and standard deviation (how spread out the numbers are). After that, it finds and shows the positions (indices) of all numbers in the array that are greater than 10. </div>

# ======================================================

<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0;">
2. Create a 2D NumPy array of shape 4 × 4 with numbers ranging from 1 to 16.<br>
&nbsp; a. Print the array.<br>
&nbsp; b. Find the transpose of the array.<br>
&nbsp; c. Calculate the row-wise and column-wise sums of the array.
</div>


In [2]:
import numpy as np

# (a) Creating a 4x4 NumPy array with values from 1 to 16

arr = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 Array:\n", arr)

print("====================================================================")

# (b) Transposed  the array

arr_transpose = arr.T
print("\nTranspose of the Array:\n", arr_transpose)

print("====================================================================")

# (c) Row-wise and Column-wise sum

row_sums = np.sum(arr, axis=1)                # Sum along rows
col_sums = np.sum(arr, axis=0)                # Sum along columns

print("\nRow-wise Sum:", row_sums)
print("Column-wise Sum:", col_sums)


Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of the Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise Sum: [10 26 42 58]
Column-wise Sum: [28 32 36 40]


<div style="background-color:#00008B; color:white; padding:10px; margin:10px 0;"> This code creates a 4x4 NumPy array with numbers from 1 to 16 arranged in order. It then finds the transpose of the array, which means flipping rows into columns. After that, it calculates the sum of each row and each column separately and prints these sums. </div>

# =======================================================

<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0;">
3. Create two 3 × 3 arrays filled with random integers between 1 and 20.<br>
&nbsp; a. Perform element-wise addition, subtraction, and multiplication.<br>
&nbsp; b. Compute the dot product of the two arrays.
</div>


In [3]:
import numpy as np

# Creating two 3x3 random integer arrays between 1 and 20

np.random.seed(42)  
arr1 = np.random.randint(1, 21, (3, 3))
arr2 = np.random.randint(1, 21, (3, 3))

print("First 3x3 Array:\n", arr1)
print("\nSecond 3x3 Array:\n", arr2)

print("================================================================")
# (a) Element-wise operations

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2

print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)

print("================================================================")
# (b) Dot Product of the two arrays

dot_product = np.dot(arr1, arr2)
print("\nDot Product of the Arrays:\n", dot_product)


First 3x3 Array:
 [[ 7 20 15]
 [11  8  7]
 [19 11 11]]

Second 3x3 Array:
 [[ 4  8  3]
 [ 2 12  6]
 [ 2  1 12]]

Element-wise Addition:
 [[11 28 18]
 [13 20 13]
 [21 12 23]]

Element-wise Subtraction:
 [[ 3 12 12]
 [ 9 -4  1]
 [17 10 -1]]

Element-wise Multiplication:
 [[ 28 160  45]
 [ 22  96  42]
 [ 38  11 132]]

Dot Product of the Arrays:
 [[ 98 311 321]
 [ 74 191 165]
 [120 295 255]]


<div style="background-color:#00008B; color:white; padding:10px; margin:10px 0;"> This code creates two 3x3 arrays filled with random integers from 1 to 20. Then, it performs element-wise addition, subtraction, and multiplication, which means these operations happen between matching positions in the two arrays. Finally, it calculates the dot product of the two arrays, which is a matrix multiplication giving a new 3x3 array. All results are printed. </div>

# ===================================================

<div style="background-color:#4B0082; color:white; padding:10px; margin:10px 0;">
4. Reshape a 1D array of size 12 into a 3 × 4 2D array and slice the first two rows and last two columns.
</div>


In [5]:
import numpy as np

# Creating a 1D array of size 12

arr = np.arange(1, 13)  # [1, 2, 3, ..., 12]

# Reshaping it into a 3x4 array

arr_2d = arr.reshape(3, 4)
print("Original 3x4 Array:\n", arr_2d)

print("-------------------------------------------------------------------------")

# Slicing First 2 rows and last 2 columns
sliced_part = arr_2d[:2, -2:]
print("\nSliced Array (First 2 Rows, Last 2 Columns):\n", sliced_part)


Original 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------------------------------------------------------------------

Sliced Array (First 2 Rows, Last 2 Columns):
 [[3 4]
 [7 8]]


<div style="background-color:#00008B; color:white; padding:10px; margin:10px 0;"> This code first creates a 1D array with numbers 1 to 12. Then, it changes the shape of this array into a 3-row by 4-column 2D array. After that, it slices and extracts the first two rows and the last two columns from this 2D array. Both the full 3x4 array and the sliced part are printed. </div>